### ISSUE TITLE
AzureBlobCache Plugin - Timeout handling

### ISSUE THREAD

**Issue by Jeavon** [JimBobSquarePants/ImageProcessor#229]
I guess sometimes Azure Blobs have problems, I have seen a few logs of 504 timeouts, I need to think about how/if to handle unexpected status codes

Example:

	System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
	   at System.Net.HttpWebRequest.GetResponse()
	   at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.RewritePath(HttpContext context)
	   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__10.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
	   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)

**Comment by JimBobSquarePants** [comment]
Hey chum! :smile: 

Is the error getting thrown here?

https://github.com/JimBobSquarePants/ImageProcessor/blob/4eaa709f3d61f0582dfd9ab254c57e181b439958/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L391

I'm not sure what the best path would be to be honest. What are your thoughts?

**Comment by Jeavon** [comment]
Hey @JimBobSquarePants 

I actually think it's being thrown here https://github.com/JimBobSquarePants/ImageProcessor/blob/4eaa709f3d61f0582dfd9ab254c57e181b439958/src/Plugins/ImageProcessor.Web/ImageProcessor.Web.Plugins.AzureBlobCache/AzureBlobCache.cs#L374

**Comment by JimBobSquarePants** [comment]
I'm not serving a stream directly when I'm getting the error. I should probably check for a timeout and serve the file from blob storage rather than the CDN if it fails. I've got 100% success with blob but about 20% with my CDN just now.

**Comment by JimBobSquarePants** [comment]
Added in the new release available on Nuget.
