### ISSUE TITLE
"Crop" with one or both dimensions greater then original does not work as expected

### ISSUE THREAD

**Issue by proff** [JimBobSquarePants/ImageProcessor#293]
Should do not crop anything at all in that dimension or just throw friendly exception in Crop method

System.ArgumentOutOfRangeException: Value cannot be less than zero or greater than the bitmap height.
Parameter name: y
   at ImageProcessor.ImageBase.get_Item(Int32 x, Int32 y) in ...\ImageProcessor\ImageBase.cs:line 133
   at ImageProcessor.Samplers.Crop.<>c__DisplayClass0_0.<Apply>b__0(Int32 y) in ...\ImageProcessor\Samplers\Crop.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

**Comment by JimBobSquarePants** [comment]
In debug mode it throws a friendlier exception. I might be best off adding a try catch to the ParallelImageProcessor class.
