### ISSUE TITLE
MaxWidth and MaxHeight - Parameter is not valid

### ISSUE THREAD

**Issue by rasmuseeg** [JimBobSquarePants/ImageProcessor#472]
Hi There,

After the security change mentioned here: #3

I'm trying to resize a image thats 6000x4000, the default settings for MaxWidth and MaxHeight does not allow resizing images greater then 5000x5000.

I just want to ask if this is inteded, and it should not just restict to the parameters (width, height) to be greater then 5000. And not the actual image being processed?

Images greather then 5000 with or height, returns Parameter is not valid, and the following:

``` 
[ArgumentException: Parameter is not valid.]
   System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format) +1143025
   ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format, Boolean preserveExifData) +588
   ImageProcessor.ImageFactory.Load(Stream stream) +332
   ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__32.MoveNext() +3680
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +71
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +9791593
```

**Comment by JimBobSquarePants** [comment]
Hi there,

Yeah the restricted values are there to prevent you resizing to larger than those dimensions. They've been there since long before the security updates so I would be keen to know what the exact querystring parameters you are sending are.

Cheers

James

**Comment by rasmuseeg** [comment]
Here is the uri:

http://localhost:51327/media/1100/drone-close-up.jpg?width=300

**Comment by rasmuseeg** [comment]
Try the following image: 
![3999](https://cloud.githubusercontent.com/assets/1511208/18629630/231ee164-7e67-11e6-8ee5-1635aca8246e.png)

**Comment by JimBobSquarePants** [comment]
Yeah. That's correct. I'll give it a wee test asap.

**Comment by rasmuseeg** [comment]
@JimBobSquarePants Thank you!

**Comment by JimBobSquarePants** [comment]
I've been unable to recreate this. I've been able to test in my solution using an
![ip-huge](https://cloud.githubusercontent.com/assets/385879/18941233/a34fadbc-8652-11e6-8b14-5ae52a2ea21b.png) multiple times without issue.


I think the thrown error message is actually a bit of a red herring. (GDI+ will do that) and you are actually running out of contiguous memory.

**Comment by xumix** [comment]
Same issue here, got 2 errors with a large image, the errors gone after recycling the app pool:
![5bc3e82c55041c477df54ce752bea6cd](https://cloud.githubusercontent.com/assets/250118/22461557/c14abe6e-e7ba-11e6-9248-6d3e0c2c1ff7.JPG)

`2017-01-31 00:00:02,573 [7] ERROR Umbraco.Core.UmbracoApplicationBase - [Thread 394] An unhandled exception occurred
System.ArgumentException: Parameter is not valid.
at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
at ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format, Boolean preserveExifData)
at ImageProcessor.ImageFactory.Load(Stream stream)
at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)`

`2017-01-31 13:24:50,765 [34] ERROR Umbraco.Core.UmbracoApplicationBase - [Thread 692] An unhandled exception occurred
System.TypeInitializationException: The type initializer for 'ImageProcessor.Web.Helpers.ImageHelpers' threw an exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at System.Reflection.AssemblyName.nGetFileInformation(String s)
at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
at ImageProcessor.Common.Helpers.TypeFinder.GetAllAssemblies()
at ImageProcessor.Common.Helpers.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
at ImageProcessor.Common.Helpers.TypeFinder.GetAssembliesWithKnownExclusions(IEnumerable`1 excludeFromResults)
at ImageProcessor.Configuration.ImageProcessorBootstrapper.LoadSupportedImageFormats()
at ImageProcessor.Configuration.ImageProcessorBootstrapper..ctor()
at ImageProcessor.Configuration.ImageProcessorBootstrapper.<>c.<.cctor>b__20_0()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at System.Lazy`1.get_Value()
at ImageProcessor.Configuration.ImageProcessorBootstrapper.get_Instance()
at ImageProcessor.Web.Helpers.ImageHelpers.BuildExtensionRegexPattern()
at ImageProcessor.Web.Helpers.ImageHelpers..cctor()
--- End of inner exception stack trace ---
at ImageProcessor.Web.Helpers.ImageHelpers.IsValidImageExtension(String fileName)
at ImageProcessor.Web.Services.LocalFileImageService.IsValidRequest(String path)
at ImageProcessor.Web.HttpModules.ImageProcessingModule.GetImageServiceForRequest(String url, String applicationPath)
at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

**Comment by xumix** [comment]
Looks like a memory leak here

**Comment by JimBobSquarePants** [comment]
It's not a memory leak. I've tested the library countless times. It's contiguous available memory on your server. Could be anything using up the bytes you don't have, FCN's other processes, anything.

**Comment by xumix** [comment]
Ok, I see.

**Comment by JimBobSquarePants** [comment]
We've done a LOT of work recently (ImageProcessor.Web v4.7.0+) reducing the amount of memory used by the server when caching images. I would suggest moving your cache outside of the webapplication and seeing what happens. This massively reduces FCN watchers reducing memory usage. 

http://imageprocessor.org/imageprocessor-web/configuration/#cacheconfig

**Comment by gardarthorsteins** [comment]
Hi, I seem to be having the same issues.

But this is only happening on Production on Azure environments.

We have it on 2 separate sites.  Both on azure. One has the caching on Azure and the other on file level but both get the same errors when trying to use any crop settings for example like ?width=300.

Small images work fine but when they go over 1300px they get the error.
Png files get Out of memory error and jpg get Parameter is not valid.

There is plenty of available memory and cpu.

Not sure what my next steps could be to fix it, your solution to move the cache from the file system did not work in this case.

@JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
Sounds to me like your Azure app is running in 32bit mode. Check your options

**Comment by oliverEvry** [comment]
@rasmuseeg  @xumix @gardarthorsteins did you find a solution to your problem? I´m exeriencing a similar one.
