### ISSUE TITLE
Exception when loading specific jpeg image on core

### ISSUE THREAD

**Issue by gdoron** [JimBobSquarePants/ImageProcessor#505]
Hi James @JimBobSquarePants,

This specific image: 
![image](https://cloud.githubusercontent.com/assets/6141009/19854753/59fbad1a-9f79-11e6-91bc-bdb8f6421ee4.png)
fails when trying to load it.

Stacktrace:

>ImageProcessorCore.Formats.JpegDecoderCore+EOFException: Exception of type 'ImageProcessorCore.Formats.JpegDecoderCore+EOFException' was thrown.
   at ImageProcessorCore.Formats.JpegDecoderCore.Fill()
   at ImageProcessorCore.Formats.JpegDecoderCore.ReadByte()
   at ImageProcessorCore.Formats.JpegDecoderCore.ReadByteStuffedByte()
   at ImageProcessorCore.Formats.JpegDecoderCore.EnsureNBits(Int32 n)
   at ImageProcessorCore.Formats.JpegDecoderCore.DecodeHuffman(Huffman huffman)
   at ImageProcessorCore.Formats.JpegDecoderCore.Refine(Block b, Huffman h, Int32 zigStart, Int32 zigEnd, Int32 delta)
   at ImageProcessorCore.Formats.JpegDecoderCore.ProcessStartOfScan(Int32 n)
   at ImageProcessorCore.Formats.JpegDecoderCore.Decode[TColor,TPacked](Image`2 image, Stream stream, Boolean configOnly)
   at ImageProcessorCore.Image`2.Decode(Stream stream)
   at ImageProcessorCore.Image`2.Load(Stream stream)
   at Yooocan.Logic.ImageLogic.Resize(Stream stream, Int32 quality, Nullable`1 width, Nullable`1 height)

Any clue?

By the way, checkout this story: https://yooocan.com/Story/329/Having-Wheels-Has-Its-Perks
Amazing people, and you're helping them James!

THANKS A LOT!

**Comment by dlemstra** [comment]
Can you add a link to the original jpg file? Github changed it into a PNG file.

**Comment by gdoron** [comment]
Try this one:
http://yooocan.com/images/temp/bad%20image.jpeg
(For future readers, this image will be deleted, I had to upload it to our server)

**Comment by gdoron** [comment]
BTW, in case you delete go to the link and read the story,
This is a Halloween costume a father made for his disabled <sub>I hate this word</sub> kid.
They "dressed" the wheelchair in a Ghostbusters car costume. **AMAZING STUFF!**.

**Comment by JimBobSquarePants** [comment]
@gdoron Great story, really heart-warming! 😄 

I'm going to move this issue over to the correct repo as I have moved everything. We can continue the discussion there.

**Comment by JimBobSquarePants** [comment]
This issue was moved to JimBobSquarePants/ImageSharp#18
