### ISSUE TITLE
Images with "crossOrigin" attribute set cause ImageProcessor.Web to break

### ISSUE THREAD

**Issue by samoruk** [JimBobSquarePants/ImageProcessor#566]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This is reproduced on the latest Umbraco (7.5.11) with Azure blob cache module. An image request with crossOrigin set causes the following error:

> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
>    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
>    at ImageProcessor.Web.HttpModules.ImageProcessingModule.AddCorsRequestHeaders(HttpContext context) in \ImageProcessor\src\ImageProcessor.Web\HttpModules\ImageProcessingModule.cs:line 265
>    at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.RewritePath(HttpContext context)
>    at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()

ImageProcessor configuration **whitelist** section is empty.

### Steps to Reproduce
In javascript code:

> var img = document.createElement("IMG");
> img.crossOrigin = "anonymous";
> img.src = "http://{valid domain}/media/312463/myroomimage.png?width=1600";

### System Configuration

- ImageProcessor version: 2.5.2
- ImageProcessor.Web version: 4.8.2
- Other ImageProcessor packages and versions: ImageProcessor.Web.Plugins.AzureBlobCache version 1.3.0
- Environment (Operating system, version and so on): Azure WebApp
- .NET Framework version:
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @samoruk 

Could you clarify the below please.

>ImageProcessor configuration whitelist section is empty.

You mean the Cors whitelist? Empty means deny all. You need to set it to `*` to be universal

http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig

Why are you setting the property anyway, as far as I'm aware that's a hack to allow setting canvas content to a src. You don't need it for what you are doing.

**Comment by samoruk** [comment]
Hi @JimBobSquarePants 

Yes, cors whitelist, sorry if didn't make it clear.

AddCorsRequestHeaders method in \ImageProcessor\src\ImageProcessor.Web\HttpModules\ImageProcessingModule.cs, line 257:

> if (origins?.WhiteList == null)
>                 {
>                        return;
>                 }

It doesn't stop here as the property is never null but has 0 entries, so it continues to create Uri with UrlEncode'ed "Origin" header and fails with the exception.

And you're correct, it's the exact use case -- loading this image to canvas. Problem is, the image comes back off azure cache (different domain) and without that property canvas becomes unusable.

**Comment by JimBobSquarePants** [comment]
@samoruk  Ah ok, thanks for the extra info, started to make more sense now. 

Could you demonstrate exactly how you have the Cors part of the config set up and I'll replicate it so I can break my test build? Should be an easy fix once I've done that.

**Comment by samoruk** [comment]
@JimBobSquarePants i'll add the config\imageprocessor\security.config file at the end but the problem seems to be with UrlEncoded'ed "Origin" header: 

`context.Request.Headers["Origin"] //"http://t.dev"`

after UrlEncode becomes:

> // Ensure origin is sanitized.
> string origin = context.Server.UrlEncode(context.Request.Headers["Origin"]); // "http%3a%2f%2ft.dev"

which is used to create Uri.

Here's the config file i've tried in the end. Also tried:
- with empty `<whitelist>` section
- some entries in `<whitelist>` section
```xml
<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    <service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web"  />
    <!--Disable the LocalFileImageService and enable this one when using virtual paths. -->
    <!--<service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Container" value=""/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://yourhost.com/"/>
      </settings>
    </service>-->
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="81943040" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="http://{azure_account}.blob.core.windows.net/media/" />
      </settings>
    </service>
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="41943040" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />
      </settings>
      <!-- <whitelist> -->
        <!-- <add url="http://images.mymovies.net"/> -->
        <!-- <add url="http://maps.googleapis.com" extensionLess="true" imageFormat=".png"/> -->
      <!-- </whitelist> -->
    </service>
  </services>
</security>
```

Hope this makes sense. I'd think sending request to image processor with `img.crossOrigin` set should break the test build.

**Comment by JimBobSquarePants** [comment]
Hey @samoruk Looks like I have a fix for the issue; I'll be pushing out an update asap with a fix. 2 days max.

Thanks for the detail helping me debug! 👍

**Comment by samoruk** [comment]
@JimBobSquarePants thank you for your lightning fast response!
