### ISSUE TITLE
hi , report bug

### ISSUE THREAD

**Issue by MajidSafari** [JimBobSquarePants/ImageProcessor#617]
hi

i use the last version image processor some times i have error

app_data\cache\e\1\6\b\d\c\e16bdcaccbc1b4f3806e7f7f116f988fea701151.jpg' because it is being used by another process

**System.IO.IOException: The process cannot access the file 'D:\RootWebPages\ir\app_data\cache\5\9\5\4\7\6\595476e46991ce2876749c417ea1cb479ac5be98.jpg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at ImageProcessor.Web.Caching.DiskCache.<AddImageToCacheAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)**

**Comment by JimBobSquarePants** [comment]
Hi @MajidSafari 

Please don't delete the issue template. It's important. As such I'm going to have to close this issue as I don't have enough detail from you.
