### ISSUE TITLE
Report bug in cache image

### ISSUE THREAD

**Issue by MajidSafari** [JimBobSquarePants/ImageProcessor#619]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageProcessor
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
```
 Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at ImageProcessor.Web.Caching.DiskCache.<AddImageToCacheAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)
```

### System Configuration

- ImageProcessor version: 2.5.4
- ImageProcessor.Web version  4.8.5
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): win 2012
- .NET Framework version: 4.6.1
- Additional information:

Request URL: https://www.iranketab.ir:443/Images/Slides/76b5746fb04c4c1caf77574d0d4df862.jpg?width=660&height=300&mode=crop 
    Request path: /Images/Slides/76b5746fb04c4c1caf77574d0d4df862.jpg

**Comment by JimBobSquarePants** [comment]
Hi @MajidSafari 

What was the actual error message? The image you've linked to is working for me and changing the querystring parameters works also.

**Comment by MajidSafari** [comment]
Hi @JimBobSquarePants 

Some times happen  this

: The process cannot access the file 'D:\RootWebPages\iranketab.ir\app_data\cache\1\7\c\0\e\f\17c0ef7b573f98e96b708945d944c53aff45e3af.jpg' because it is being used by another process.

**Comment by MajidSafari** [comment]
ImageProcessingModule.ValidatingRequest += (senderr, args) =>
            {
                if (!string.IsNullOrWhiteSpace(args.QueryString))
                {


                 
                    var queryCollection = HttpUtility.ParseQueryString(args.QueryString);

                    queryCollection.Add("bgcolor", "fff");
                    queryCollection.Add("contrast", "25");
                    args.QueryString = queryCollection.ToString();


                  
                }
            };



i just add this ,

**Comment by JimBobSquarePants** [comment]
What has this got to do with the raised issue? Please don't waste my time.
