### ISSUE TITLE
Umbraco /remote.axd - System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required

### ISSUE THREAD

**Issue by mistyn8** [JimBobSquarePants/ImageProcessor#646]
### Prerequisites

- [**x**] I have written a descriptive issue title
- [**x**] I have verified that I am running the latest version of ImageProcessor
- [**x**] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [**x**] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issuess) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Umbraco 7.7.7 using remote.axd with whitelisted 
`<add url="https://scontent.cdninstagram.com"/>`

`/remote.axd?https://scontent.cdninstagram.com/vp/7bceb01dd30ee7a725b67cbc0c7b5d7d/5AF34E11/t51.2885-15/sh0.08/e35/p640x640/26156543_895553167283443_4603104630820306944_n.jpg?width=640&height=640&mode=crop`

and the alternative

`/remote.axd/scontent.cdninstagram.com/vp/7bceb01dd30ee7a725b67cbc0c7b5d7d/5AF34E11/t51.2885-15/sh0.08/e35/p640x640/26156543_895553167283443_4603104630820306944_n.jpg?width=640&height=640&mode=crop`

both return a server 500 error

full entry in the log
```
2018-01-15 13:50:21,220 [P7248/D85/T28] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ImageProcessor.Web.Helpers.RemoteFile.<GetWebResponseAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ImageProcessor.Web.Services.RemoteImageService.<GetImage>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)
```

I've had a similar issue using the inbuilt Umbraco with twitter feeds

```
public static XPathNodeIterator GetXmlDocumentByUrl(string Url)
        {
            XmlDocument xmlDoc = new XmlDocument();
            WebRequest request = WebRequest.Create(Url);
```

by adding 
` request.Proxy.Credentials = CredentialCache.DefaultCredentials;`

that was resolved.

Looking at the source code for RemoteFile > internal GetWebRequest() you already have that, so not sure why I'm seeing this proxying issue.

### System Configuration

- ImageProcessor version: **2.5.6.0**
- ImageProcessor.Web version (if applicable) **4.8.7.0**
- Other ImageProcessor packages and versions:
- Environment (Operating system, version and so on): **windows 8 - iis express via vs 2017 community - localhost access with proxy via group policy**
- .NET Framework version: **4.6**
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @mistyn8 

I'm at a loss. It's working perfectly for me. Maybe, somehow, Umbraco is doing something wonky.

![remote](https://user-images.githubusercontent.com/385879/35564237-98f9a066-060d-11e8-9edb-8714db0a459f.JPG)
