### ISSUE TITLE
Method not found: get_ImageCacheMaxMinutes()

### ISSUE THREAD

**Issue by lesley-w** [JimBobSquarePants/ImageProcessor#683]
We are replacing ImageGen in our Umbraco website with ImageProcessor, and also moving the media folder and caching to Azure Blob storage.

These are the ImageProcessor packages we have installed:

```
  <package id="ImageProcessor" version="2.6.1.19" targetFramework="net452" />
  <package id="ImageProcessor.Web" version="4.9.2.19" targetFramework="net452" />
  <package id="ImageProcessor.Web.Config" version="2.4.1.19" targetFramework="net452" />
  <package id="ImageProcessor.Web.Plugins.AzureBlobCache" version="1.4.2.19" targetFramework="net452" />
```

When attempting to run the Azure website we get the following error in the log:

```
Method not found: 'Int32 ImageProcessor.Web.Caching.ImageCacheBase.get_ImageCacheMaxMinutes()'.
   at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.&lt;IsNewOrUpdatedAsync&gt;d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine&amp; stateMachine)
   at ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache.IsNewOrUpdatedAsync()
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.&lt;ProcessImageAsync&gt;d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)

```

**Comment by lesley-w** [comment]
The dependencies for AzureBlobCache are showing as:
```
ImageProcessor.Web (>= 4.9.2)
ImageProcessor.Web.Config (>= 2.4.1)
```
but I upgraded ImageProcessor to 2.6.2.25 and ImageProcessor.Web to 4.9.3.25 and that seems to have fixed it.

Thanks for the quick response!

**Comment by JimBobSquarePants** [comment]
Thanks @lesley-w 

I must have forgotten to update them. I'll bump up the dependency versions for the next release 👍
