### ISSUE TITLE
IndexOutOfRangeException in ImageProcessor.Web.Processors.Crop.MatchRegexIndex

### ISSUE THREAD

**Issue by ronaldbarendse** [JimBobSquarePants/ImageProcessor#706]
I've gotten some `IndexOutOfRangeException`s recently with the following stack trace:

```c#
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at ImageProcessor.Web.Processors.Crop.MatchRegexIndex(String queryString)
at ImageProcessor.Web.ImageFactoryExtensions.<>c__DisplayClass1_0.<GetMatchingProcessors>b__0(IWebGraphicsProcessor x)
at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at ImageProcessor.Web.ImageFactoryExtensions.GetMatchingProcessors(String querystring)
at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__35.MoveNext()
```

The request URLs generating this exception contained an invalid crop query parameter: `?crop=0`. Looking into it, there's no guarding on the parsed `coordinates` array:

https://github.com/JimBobSquarePants/ImageProcessor/blob/58e18acd42de65b02421a85dee5361c4d74ac2ff/src/ImageProcessor.Web/Processors/Crop.cs#L68-L73

Avoiding this seems quite trivial: just add a `null` and `Length` check on `coordinates`, but I don't know if that just moves the exception to the `ImageProcessor.Web.Processors.Crop` processor... So maybe the regex should be changed to add this piece of validation?

**Comment by ronaldbarendse** [comment]
There's no reason throw and catch exceptions in this case, it's just about correctly validating user input before using it...

Searching through the code, returning `int.MaxValue` in `MatchRegexIndex` skips the processor:

https://github.com/JimBobSquarePants/ImageProcessor/blob/eba1804d18ab492862c8bdf8da7c72a7e215bf85/src/ImageProcessor.Web/ImageFactoryExtensions.cs#L65-L68

So I've already created a PR to fix this! 😄
