### ISSUE TITLE
IP behaves different on VM

### ISSUE THREAD

**Issue by Excludos** [JimBobSquarePants/ImageProcessor#761]
I'm trying to concatenate a bunch of images vertically, and then resize them down a bit. It works fine on my local computer, but this is meant to run on a VM, at which point I ran into these issues:

`ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with BackgroundColor ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at ImageProcessor.Processors.BackgroundColor.ProcessImage(ImageFactory factory)
   --- End of inner exception stack trace ---
   at ImageProcessor.Processors.BackgroundColor.ProcessImage(ImageFactory factory)
   at ImageProcessor.Imaging.Formats.FormatBase.ApplyProcessor(Func'2 processor, ImageFactory factory) at ImageProcessor.ImageFactory.BackgroundColor(Color color)`

Removing BackroundColor(Color.White) from the code almost makes it work, but then at the very end, where I ask to resize it down from roughly 30k pixels height to 10k (Width is static at 154), it hits me with another:

`ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resize ---> ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resizer ---> System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format, Boolean preserveExifData)
   at ImageProcessor.Imaging.Resizer.ResizeLinear(Image source, Int32 width, Int32 height, Rectangle destination, AnimationProcessMode animationProcessMode)
   at ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Int32 width, Int32 height, Int32 maxWidth, Int32 maxHeight, List'1 restrictedSizes, ResizeMode resizeMode, AnchorPosition anchorPosition, Boolean upscale, Single[] centerCoordinates, Boolean linear, Nullable'1 anchorPoint)
   --- End of inner exception stack trace ---
   at ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Int32 width, Int32 height, Int32 maxWidth, Int32 maxHeight, List'1 restrictedSizes, ResizeMode resizeMode, AnchorPosition anchorPosition, Boolean upscale, Single[] centerCoordinates, Boolean linear, Nullable'1 anchorPoint)
   at ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Boolean linear)
   at ImageProcessor.Processors.Resize.ProcessImage(ImageFactory factory)
   --- End of inner exception stack trace ---
   at ImageProcessor.Processors.Resize.ProcessImage(ImageFactory factory)
   at ImageProcessor.Imaging.Formats.FormatBase.ApplyProcessor(Func'2 processor, ImageFactory factory) at ImageProcessor.ImageFactory.Resize(ResizeLayer resizeLayer)`

Resize worked fine on the individual images, but not on the larger finished product.

The VM runs Windows Server 2019 Datacenter, a Xeon CPU E5-2673 v3 @ 2.40GHz, 32Gb ram, and 64 bit Os.

**Comment by Excludos** [comment]
It is possible the "AnyCPU" setting made application believe it should be running 32bit on the VM for whatever reason, at which point the latter error is reasonable if it ran out of memory. The first error is still a bit weird, but probably related. Forcing 64 bit fixes the issue
