### ISSUE TITLE
Image processing for {static image} has been cancelled by an event / Error processing image with Resize

### ISSUE THREAD

**Issue by ja0b** [JimBobSquarePants/ImageProcessor#814]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi James, TBH I don't know if this is an ImageProcessor issue but the logs point to it even though I haven't been able to exactly pinpoint it. Hope you can maybe throw some ideas to finally solve this issue. There are 2 errors that keep happening on this site what I don't understand is why ImageProcessor try to do something with static images when no ImageProcessor query strings have been set to it, this happens every time this request results in a 503 or a 404 see:

1. 
```
Same for 503 - 404
--------------------
Error occurred performing GET for xxxx/xxxx/xxxx/xxxx/xxxx
System.Net.Http.HttpRequestException: Response status code does not indicate success: 503 (Service Unavailable).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at xxxx.WebClient.xxxx.GetAsString(String parameters) in D:\a\1\s\xxxx\WebClient\xxxx.cs:line 45
2020-08-20 00:45:56,951 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/bg-blue.png?1554798686 has been cancelled by an event
2020-08-20 00:45:56,964 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/twitter/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:45:58,258 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/footer/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:45:58,732 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/twitter/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:45:58,736 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/bg-blue.png?1554798686 has been cancelled by an event
2020-08-20 00:45:58,767 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/footer/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:45:59,143 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/bg-blue.png?1554798686 has been cancelled by an event
2020-08-20 00:45:59,143 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/twitter/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:45:59,145 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/footer/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:46:00,060 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/bg-blue.png?1554798686 has been cancelled by an event
2020-08-20 00:46:00,083 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/twitter/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:46:00,159 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/footer/bg.png?1554798686 has been cancelled by an event
```

2. 
```
Logger	Umbraco.Core.UmbracoApplicationBase
An unhandled exception occurred
ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resize ---> ImageProcessor.Common.Exceptions.ImageProcessingException: Error processing image with Resizer ---> System.InvalidOperationException: Target width 0 and height 0 must be greater than zero.
   at ImageProcessor.Imaging.ResizeHelper.ThrowInvalid(String message)
   at ImageProcessor.Imaging.ResizeHelper.CalculateTargetLocationAndBounds(Size sourceSize, ResizeLayer options, Int32 width, Int32 height)
   at ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Boolean linear)
   --- End of inner exception stack trace ---
   at ImageProcessor.Imaging.Resizer.ResizeImage(Image source, Boolean linear)
   at ImageProcessor.Processors.Resize.ProcessImage(ImageFactory factory)
   --- End of inner exception stack trace ---
   at ImageProcessor.Processors.Resize.ProcessImage(ImageFactory factory)
   at ImageProcessor.Imaging.Formats.FormatBase.ApplyProcessor(Func`2 processor, ImageFactory factory)
   at ImageProcessor.Web.ImageFactoryExtensions.AutoProcess(ImageFactory factory, IWebGraphicsProcessor[] graphicsProcessors)
   at ImageProcessor.Web.HttpModules.ImageProcessingModule.<ProcessImageAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.InvokeEndHandler(IAsyncResult ar)
   at System.Web.HttpApplication.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar)
2020-08-20 00:25:58,571 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/homepage/social-bar/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:25:58,664 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/homepage/random-lookup/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:25:59,101 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/bg-blue.png?1554798686 has been cancelled by an event
2020-08-20 00:25:59,102 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/twitter/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:25:59,363 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/footer/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:25:59,471 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/bg-blue.png?1554798686 has been cancelled by an event
2020-08-20 00:25:59,489 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/sidebar/twitter/bg.png?1554798686 has been cancelled by an event
2020-08-20 00:25:59,937 [123] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 483 : Image processing for /img/footer/bg.png?1554798686 has been cancelled by an event
```

### System Configuration

- ImageProcessor version: 2.9.1
- ImageProcessor.Web version (if applicable): 4.12.1
- Other ImageProcessor packages and versions: ImageProcessor.Web.Config 2.6.0
- Environment (Operating system, version and so on): VM (Windows Server 2016 Datacenter) on AWS using a virtual directory to host the media.
- .NET Framework version: 4.7.2
- Additional information: Umbraco 7.15.5

**Comment by ja0b** [comment]
Got an answer from the slack community help channel:

_jimbobsquarepants
There are querystrings however ?1554798686 and ImageProcessor will attempt to recognise and parse them.
I would say the lack of a key/value pair in the querystring values is causing issue. I would pull down the source code and create a similar request in the sample application. Then you can attach a debugger and see what is happening. (edited)_ 

I'll give it a try and update this issue with the results, thanks for your help!! 👍

**Comment by ronaldbarendse** [comment]
I've seen the same `ImageProcessingException` on URLs that use some strange encoding in the query string, e.g.: `?anchor=center&amp%3Bmode=crop&amp%3Bwidth=600&amp%3Bheight=450&amp%3Bpreset=product&amp%3Brnd=131950648910000000` (notice the `&amp` and `%3B`, probably a combination of HTML and URL encoding).

They were all from bots/spiders, so it's not a real problem, but it would be nice if these requests didn't fill the log with exceptions/errors...

@JimBobSquarePants Should ImageProcessor silently stop processing these request and let the server return the original image or return a `404 Bad Request` instead?

@ja0b It doesn't look like the `HttpRequestException`/503 error is coming from ImageProcessor. All other `ImageProcessingException`s are caused by cancelling the `ImageProcessingModule.ValidatingRequest` event, so that's probably some custom code, see: https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/#events.

**Comment by JimBobSquarePants** [comment]
401 you mean yeah? Possibly. We have a request validation event that people should use if they're having issues though.

**Comment by ronaldbarendse** [comment]
> 401 you mean yeah?

I meant a [400](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) indeed (I've updated my comment) 👍

This problem is caused by the fact that the `IWebGraphicsProcessor`s check the query string using regex matches. So the resize processor matches on the `width` or `height` part of the query string, but can't parse the parameters (or the values), so both dimensions end up being 0 and the exception is thrown:

https://github.com/JimBobSquarePants/ImageProcessor/blob/e1b931a2d33a98cac6b2f90a6b612db875fb3313/src/ImageProcessor.Web/Processors/Resize.cs#L34

https://github.com/JimBobSquarePants/ImageProcessor/blob/2b02bb83423ff19a9405cab9f9d7865e0e0779c3/src/ImageProcessor/Imaging/ResizeHelper.cs#L38-L41

**Comment by JimBobSquarePants** [comment]
In that case yes, but the query string can/should be reviewed on validation

**Comment by mitraganesh** [comment]
> Got an answer from the slack community help channel:
> 
> _jimbobsquarepants There are querystrings however ?1554798686 and ImageProcessor will attempt to recognise and parse them. I would say the lack of a key/value pair in the querystring values is causing issue. I would pull down the source code and create a similar request in the sample application. Then you can attach a debugger and see what is happening. (edited)_
> 
> I'll give it a try and update this issue with the results, thanks for your help!!

Hi @ja0b 

How did you resolved this? I am experience the same issue

**Comment by ronaldbarendse** [comment]
@mitraganesh That message is only logged when you manually cancel the event in `ImageProcessingModule.ValidatingRequest`:

https://github.com/JimBobSquarePants/ImageProcessor/blob/b2b9387d8774a3a6f054389740bd5623ca7d7e59/src/ImageProcessor.Web/HttpModules/ImageProcessingModule.cs#L476-L485

You're probably using Umbraco, as that logs all messages as errors encapsulated in an `ImageProcessingException` (see [`Umbraco.Web/ImageProcessorLogger`](https://github.com/umbraco/Umbraco-CMS/blob/f29c5f0e3b0dc79456e2726f3aeace04e51a28b0/src/Umbraco.Web/ImageProcessorLogger.cs)).

**Comment by mitraganesh** [comment]
@ronaldbarendse 
Thanks for you reply.

Yes you are right, I am using umbraco. So we can ignore that error message right?

**Comment by ronaldbarendse** [comment]
@mitraganesh If it's not causing other problems, you can ignore it indeed 👍
