### ISSUE TITLE
"Parameter is not valid." when creating WebP from Bitmap

### ISSUE THREAD

**Issue by jeffffc** [JimBobSquarePants/ImageProcessor#829]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageProcessor
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/JimBobSquarePants/ImageProcessor/issues) and [closed](https://github.com/JimBobSquarePants/ImageProcessor/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Probably related to #531?
It is a .NET Core 3.1 Console app.

On linux (ubuntu):
Upon reaching `imageFactory.Load()`, I got "Parameter is not valid." error.

On Windows (dev env, VS 2019):
No problem and WebP successfully saved to stream.

Traceback:
```
Parameter is not valid.

   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi)
   at ImageProcessor.Common.Extensions.ImageExtensions.Copy(Image source, AnimationProcessMode animationProcessMode, PixelFormat format, Boolean preserveExifData)
   at ImageProcessor.ImageFactory.Load(Image image)
   at MyProject.MyClass.ToStream(Image image, ImageFormat format) in C:\Users\user\source\repos\MySolution\MyProject\MyClass.cs:line 505
```

### Steps to Reproduce
```
using System.Drawing;
using System.Drawing.Imaging;
using ImageProcessor;
using ImageProcessor.Plugins.WebP.Imaging.Formats;

private Stream ToStream(Image image, ImageFormat format)
{
    var stream = new System.IO.MemoryStream();
    using (Bitmap img = new Bitmap(image))
    {
        using (ImageFactory imageFactory = new ImageFactory(preserveExifData: false))
        {
           imageFactory.Load(img).Format(new WebPFormat()).Quality(100).Save(stream);
        }
        stream.Position = 0;
    }
    return stream;
}
```

### System Configuration

- ImageProcessor version: 2.9.1
- ImageProcessor.Web version (if applicable): --
- Other ImageProcessor packages and versions: ImageProcessor.Plugins.WebP 1.3.0
- Environment (Operating system, version and so on): VPS with 4GB ram / Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-54-generic x86_64)
- .NET Framework version: .NET Core 3.1
- Additional information:

**Comment by jeffffc** [comment]
Sorry, read from some other issues that I might need to switch to https://github.com/SixLabors/ImageSharp for dotnet core projects. Will close this now. Thanks.
