### ISSUE TITLE
Error loading ImageProcessor assembly

### ISSUE THREAD

**Issue by lxman** [JimBobSquarePants/ImageProcessor#836]
I have created a simple winform project (.NET 4.8) to try and learn ImageProcessor. When trying to load an image I receive the following:

`System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'ImageProcessor.ImageFactory' from assembly 'ImageProcessor, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=ImageProcessor
  StackTrace:
   at ImageProcessor.Form1.LoadButton_Click(Object sender, EventArgs e) in C:\Users\jorda\source\repos\ImageProcessor\ImageProcessor\Form1.cs:line 42
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at ImageProcessor.Program.Main() in C:\Users\jorda\source\repos\ImageProcessor\ImageProcessor\Program.cs:line 16`

`

**Comment by ronaldbarendse** [comment]
Hi @lxman, what version of ImageProcessor did you install? The exception clearly shows it's expecting version 1.0.0, which doesn't exist on your system/bin folder. The latest version as of this writing is [2.9.1](https://www.nuget.org/packages/ImageProcessor/2.9.1).

Make sure the project is referencing the right version and you don't have an assembly redirect that points to a nonexistent version. This isn't a bug with ImageProcessor, so I'll close this issue for that reason.
